name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: actions/checkout@v2
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2
      - name: actions/setup-node@v1
        if: ${{ github.event_name == 'push' }}      
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: npm install
        if: ${{ github.event_name == 'push' }}
        run: npm install
      # - name: lint
      #   run: npm run eslint
      # - name: e2e tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000
      - name: akhileshns/heroku-deploy@v3.8.9
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fullstack-zq-pokedex"
          heroku_email: "mapplezq@gmail.com"
          healthcheck: "https://fullstack-zq-pokedex.herokuapp.com/version"
          checkstring: "0.0.1"          
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch